export const WORKCHAIN_ESCROW_ADDRESS = '0xf792cA409B09FA9bE110fF9F3DF9e24336c31233' as const

export const WORKCHAIN_ESCROW_ABI = [
  {
    type: 'function',
    name: 'proposeContract',
    inputs: [
      { name: '_freelancer', type: 'address' },
      { name: '_title', type: 'string' },
      { name: '_description', type: 'string' },
      { name: '_paymentType', type: 'uint8' },
      { name: '_totalAmount', type: 'uint256' },
      { name: '_deadline', type: 'uint256' },
      { name: '_recurringAmount', type: 'uint256' },
      { name: '_recurringInterval', type: 'uint256' },
      { name: '_recurringCount', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'addMilestones',
    inputs: [
      { name: '_contractId', type: 'uint256' },
      { name: '_descriptions', type: 'string[]' },
      { name: '_amounts', type: 'uint256[]' },
      { name: '_deadlines', type: 'uint256[]' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'signAndActivate',
    inputs: [{ name: '_contractId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'releaseMilestone',
    inputs: [
      { name: '_contractId', type: 'uint256' },
      { name: '_milestoneIndex', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'releaseRecurringPayment',
    inputs: [{ name: '_contractId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'requestExtension',
    inputs: [
      { name: '_contractId', type: 'uint256' },
      { name: '_newDeadline', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'approveExtension',
    inputs: [{ name: '_contractId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'markExpired',
    inputs: [{ name: '_contractId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'raiseDispute',
    inputs: [{ name: '_contractId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'resolveDispute',
    inputs: [
      { name: '_contractId', type: 'uint256' },
      { name: '_winner', type: 'address' },
      { name: '_amount', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'cancelContract',
    inputs: [{ name: '_contractId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getContract',
    inputs: [{ name: '_contractId', type: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'client', type: 'address' },
          { name: 'freelancer', type: 'address' },
          { name: 'title', type: 'string' },
          { name: 'description', type: 'string' },
          { name: 'paymentType', type: 'uint8' },
          { name: 'status', type: 'uint8' },
          { name: 'totalAmount', type: 'uint256' },
          { name: 'createdAt', type: 'uint256' },
          { name: 'deadline', type: 'uint256' },
          { name: 'clientSigned', type: 'bool' },
          { name: 'freelancerSigned', type: 'bool' },
          { name: 'recurringAmount', type: 'uint256' },
          { name: 'recurringInterval', type: 'uint256' },
          { name: 'lastPaymentAt', type: 'uint256' },
          { name: 'recurringCount', type: 'uint256' },
          { name: 'recurringPaid', type: 'uint256' },
          { name: 'extensionRequestedBy', type: 'uint256' },
          { name: 'proposedDeadline', type: 'uint256' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getMilestones',
    inputs: [{ name: '_contractId', type: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple[]',
        components: [
          { name: 'description', type: 'string' },
          { name: 'amount', type: 'uint256' },
          { name: 'deadline', type: 'uint256' },
          { name: 'released', type: 'bool' },
          { name: 'disputed', type: 'bool' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'contractCount',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
] as const