export const WORKCHAIN_ESCROW_ADDRESS = '0xEa04d926132eEA022E676B2A842E7CaD6Ec36aEF' as const

export const WORKCHAIN_ESCROW_ABI = [
  {
    type: 'function',
    name: 'postOpenJob',
    inputs: [
      { name: '_title', type: 'string' },
      { name: '_description', type: 'string' },
      { name: '_category', type: 'string' },
      { name: '_paymentType', type: 'uint8' },
      { name: '_totalAmount', type: 'uint256' },
      { name: '_deadline', type: 'uint256' },
      { name: '_recurringAmount', type: 'uint256' },
      { name: '_recurringInterval', type: 'uint256' },
      { name: '_recurringCount', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'proposeDirectContract',
    inputs: [
      { name: '_freelancer', type: 'address' },
      { name: '_title', type: 'string' },
      { name: '_description', type: 'string' },
      { name: '_category', type: 'string' },
      { name: '_paymentType', type: 'uint8' },
      { name: '_totalAmount', type: 'uint256' },
      { name: '_deadline', type: 'uint256' },
      { name: '_recurringAmount', type: 'uint256' },
      { name: '_recurringInterval', type: 'uint256' },
      { name: '_recurringCount', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'applyForJob',
    inputs: [
      { name: '_contractId', type: 'uint256' },
      { name: '_coverNote', type: 'string' },
      { name: '_proposedRate', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'selectFreelancer',
    inputs: [
      { name: '_contractId', type: 'uint256' },
      { name: '_freelancer', type: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'addMilestones',
    inputs: [
      { name: '_contractId', type: 'uint256' },
      { name: '_descriptions', type: 'string[]' },
      { name: '_amounts', type: 'uint256[]' },
      { name: '_deadlines', type: 'uint256[]' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'signAndActivate',
    inputs: [{ name: '_contractId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'releaseMilestone',
    inputs: [
      { name: '_contractId', type: 'uint256' },
      { name: '_milestoneIndex', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'releaseRecurringPayment',
    inputs: [{ name: '_contractId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'requestExtension',
    inputs: [
      { name: '_contractId', type: 'uint256' },
      { name: '_newDeadline', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'approveExtension',
    inputs: [{ name: '_contractId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'markExpired',
    inputs: [{ name: '_contractId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'raiseDispute',
    inputs: [{ name: '_contractId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'resolveDispute',
    inputs: [
      { name: '_contractId', type: 'uint256' },
      { name: '_winner', type: 'address' },
      { name: '_amount', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'cancelContract',
    inputs: [{ name: '_contractId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getContract',
    inputs: [{ name: '_contractId', type: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'client', type: 'address' },
          { name: 'freelancer', type: 'address' },
          { name: 'title', type: 'string' },
          { name: 'description', type: 'string' },
          { name: 'category', type: 'string' },
          { name: 'paymentType', type: 'uint8' },
          { name: 'contractType', type: 'uint8' },
          { name: 'status', type: 'uint8' },
          { name: 'totalAmount', type: 'uint256' },
          { name: 'createdAt', type: 'uint256' },
          { name: 'deadline', type: 'uint256' },
          { name: 'clientSigned', type: 'bool' },
          { name: 'freelancerSigned', type: 'bool' },
          { name: 'recurringAmount', type: 'uint256' },
          { name: 'recurringInterval', type: 'uint256' },
          { name: 'lastPaymentAt', type: 'uint256' },
          { name: 'recurringCount', type: 'uint256' },
          { name: 'recurringPaid', type: 'uint256' },
          { name: 'extensionRequestedBy', type: 'uint256' },
          { name: 'proposedDeadline', type: 'uint256' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getMilestones',
    inputs: [{ name: '_contractId', type: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple[]',
        components: [
          { name: 'description', type: 'string' },
          { name: 'amount', type: 'uint256' },
          { name: 'deadline', type: 'uint256' },
          { name: 'released', type: 'bool' },
          { name: 'disputed', type: 'bool' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getApplications',
    inputs: [{ name: '_contractId', type: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple[]',
        components: [
          { name: 'freelancer', type: 'address' },
          { name: 'coverNote', type: 'string' },
          { name: 'proposedRate', type: 'uint256' },
          { name: 'appliedAt', type: 'uint256' },
          { name: 'selected', type: 'bool' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getApplicationCount',
    inputs: [{ name: '_contractId', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'contractCount',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
] as const
export const WORKCHAIN_REPUTATION_ADDRESS = '0x979A77f031F7EcE73b81E827a8BB5De7BDca848a' as const

export const WORKCHAIN_REPUTATION_ABI = [
  {
    type: 'function',
    name: 'getCredential',
    inputs: [{ name: '_tokenId', type: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'freelancer', type: 'address' },
          { name: 'client', type: 'address' },
          { name: 'jobTitle', type: 'string' },
          { name: 'category', type: 'string' },
          { name: 'amount', type: 'uint256' },
          { name: 'completedAt', type: 'uint256' },
          { name: 'contractId', type: 'uint256' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getFreelancerCredentials',
    inputs: [{ name: '_freelancer', type: 'address' }],
    outputs: [{ name: '', type: 'uint256[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getFreelancerCredentialCount',
    inputs: [{ name: '_freelancer', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'tokenCount',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'CredentialMinted',
    inputs: [
      { name: 'tokenId', type: 'uint256', indexed: true },
      { name: 'freelancer', type: 'address', indexed: true },
      { name: 'client', type: 'address', indexed: true },
      { name: 'contractId', type: 'uint256', indexed: false },
      { name: 'jobTitle', type: 'string', indexed: false },
    ],
  },
] as const